all:
  vars:
    ansible_user: root
    ansible_password: changeme123
  children:
    wordpress:
      hosts:
        wp-01:
          ansible_host: 10.24.36.10
          ct_id: 100
          ssh_user: user1
        wp-02:
          ansible_host: 10.24.36.11
          ct_id: 101
          ssh_user: user2
        wp-03:
          ansible_host: 10.24.36.12
          ct_id: 102
          ssh_user: user3
    monitoring:
      hosts:
        monitoring-server:
          ansible_host: 10.24.36.20
